#1430 disable selection dialog on not physical containters
Open-Systems-Pharmacology/MoBi pull request #1471
Opened 2024-08-06 16:26 UTC by benjaperez1983

Fixes #1430

# Description

disable selection dialog on not physical containters selected

## Type of change

Please mark relevant options with an `x` in the brackets.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [ ] Unit tests
- [x] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):

# Questions (if appropriate):

2024-08-12 10:53 UTC, rwmcintosh requested changes
Can you create a test for this?

2024-08-12 12:03 UTC, benjaperez1983 commented
> Can you create a test for this?

Done!

2024-08-12 13:40 UTC, rwmcintosh approved these changes

2024-08-14 09:15 UTC, Yuri05 approved these changes

2024-08-14 10:58 UTC, merged