1578 commit to bb
Open-Systems-Pharmacology/MoBi pull request #1593
Opened 2024-10-22 15:38 UTC by benjaperez1983

Fixes #1578

# Description

Add message with confirmation and information when commiting to BB From simulation

## Type of change

Please mark relevant options with an `x` in the brackets.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [ ] Unit tests
- [x] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):
If last module has building blocks selected
![image](https://github.com/user-attachments/assets/b548f7a3-5e5d-4a49-b9e0-2c423bc29831)

if no building blocks are selected
![image](https://github.com/user-attachments/assets/a3fb31c6-b941-43bb-98f6-e1cc64f53c86)

# Questions (if appropriate):

2024-10-24 16:11 UTC, rwmcintosh approved these changes
Just fix up those minor comments and add Juri.

2024-10-24 16:11 UTC, rwmcintosh commented on src/MoBi.Presentation/Tasks/SimulationCommitTask.cs
> +         var valueTuples = parameterChanges;
you don't need that assignment now

2024-10-24 16:11 UTC, rwmcintosh commented on src/MoBi.Presentation/Tasks/SimulationCommitTask.cs
> +         var valueTuples = moleculeChanges;
or that one.

2024-10-24 16:11 UTC, rwmcintosh commented on src/MoBi.Presentation/UICommand/CommitSimulationUICommand.cs
> +         if(command!= null)
just fix up the spacing on `command!= null`

2024-10-24 20:52 UTC, rwmcintosh requested changes
I didn't realize that the build has failed

2024-10-24 20:53 UTC, rwmcintosh commented
> I didn't realize that the build has failed

It's probably because you need a fake on the dialog box

2024-10-28 16:45 UTC, rwmcintosh approved these changes

2024-10-28 17:08 UTC, Yuri05 approved these changes

2024-10-28 17:09 UTC, merged