796 make sure we load
Open-Systems-Pharmacology/MoBi pull request #797
Opened 2022-11-12 01:53 UTC by msevestre

2022-11-12 01:54 UTC, msevestre commented
I have fixed quite a few bugs at the same time. 
For instance, OutputMappings were not serilaized at all in MoBi

2022-11-12 01:55 UTC, msevestre commented on src/MoBi.Core/Domain/Model/MoBiSimulation.cs
> +         return OutputMappings.Any(x => x.UsesObservedData(dataRepository)) || Charts.Any(x => chartUsesObservedData(dataRepository, x));
I think this is a good way to check if an observed data is used. Either it's used in the chart or it's referenced in the output mappings.

2022-11-12 01:56 UTC, msevestre commented on src/MoBi.Core/Domain/Services/CloneManagerForSimulation.cs
> +            MoleculesInfo = CloneBuildingBlockInfo(simulationToClone.MoBiBuildConfiguration.MoleculesInfo),
typo

2022-11-12 01:57 UTC, msevestre commented on src/MoBi.Core/Serialization/Services/DeserializedReferenceResolver.cs
> +         outputMappings.Each(x => x.UpdateSimulation(simulation));
I am not quite SURE why this is required. But MoBi does not use the SimulationLoader. Instead something else is used and that creates issue with references

2022-11-14 12:15 UTC, rwmcintosh requested changes
Just that typo to fix please.

2022-11-14 13:28 UTC, msevestre commented
@rwmcintosh I think those changes can be done by the reviewer if it's only a little thing? This is probably much faster than back and forth. We could discuss what makes sense

2022-11-14 13:30 UTC, msevestre reviewed
Update typos

2022-11-14 13:31 UTC, merged

2022-11-14 13:44 UTC, rwmcintosh commented
> @rwmcintosh I think those changes can be done by the reviewer if it's only a little thing? This is probably much faster than back and forth. We could discuss what makes sense

Oh, like in the editor if it's just a comment typo? Yeah, that makes sense.